[package]
name = "tvm-tests"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
tvm-core = { path = "../tvm-core" }

[dev-dependencies]
tvm-core = { path = "../tvm-core" }
tvm-wasmtime = { path = "../tvm-wasmtime" }
tvm-guest-mm = { path = "../tvm-guest-mm" }
tempfile = "3"
